bbsnote/urls.py
from django.urls import path
from . import views

app_name = 'bbsnote'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'), # <board_id라는 숫자>가 넘어올 것이다
    path('comment/create/<int:board_id>/', views.comment_create, name='comment_create'),
    path('board/create/', views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>/', views.board_delete, name='board_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name='common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bbsnote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbsnote/', include('bbsnote.urls')), # 주소가 127.~~~/bbsnote이면 views.py의 index가 나오도록 설정함
    path('common/', include('common.urls')),
    path('', views.index,name='index'), # 주소창에 아무것도 없어도 오류창 안 뜨고 bbsnote처럼 나오게 설정한 것
    
]

bbsnote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Board(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True) # 작성되는 시간이 자동적으로 반영됨
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.id}]{self.subject}'

class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-create_date']

    def __str__(self):
        return f'[{self.board.id}]{self.content}'

bbsnote/forms.py
from django import forms
from bbsnote.models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['subject','content']
        # widgets={
        #     'subject' : forms.TextInput(attrs={'class':'form-control'}), # forms의 TextInput에 attribute를 추가시킬게
        #     'content' : forms.Textarea(attrs ={'class':'form-control', 'rows':10})
        # }
        # labels={
        #     'subject' : '제목',
        #     'content' : '내용',
        # }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']
        labels={
            'content' : '댓글내용'

        }

bbsnote/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Board, Comment
from django.utils import timezone
from .forms import BoardForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def index(request):
    # 입력인자 추가
    # 페이지정보 값이 따라다님
    # 요청된 정보로부터 GET방식으로 넘어오는 데이터중에 page라는 값을 가져오고, 없으면 1로 초기화(주소에 page값 입력하지 않으면 1페이지를 기본으로 보여줘라)
    page = request.GET.get('page',1)
    # 조회
    board_list = Board.objects.order_by('-create_date')
    # 페이징처리
    # paginator라는 변수에 boad_list에 있는 데이터를 5개씩 쪼개 담는다(한 page에 글 5개씩 보여주기 위함)
    paginator = Paginator(board_list, 5)
    # 위에서 정의한 page변수를 넘겨받아서 그 page에 해당하는 정보를 page_obj에 저장하고 board_list로 넘겨준다
    page_obj=paginator.get_page(page)
    context={'board_list' : page_obj} # 사전형

    # return HttpResponse("bbsnote에 오신 것을 환영합니다")
    return render(request, 'bbsnote/board_list.html', context)

def detail(request, board_id): # 주소에서 board_id 넘겨받음
    board = Board.objects.get(id=board_id) # board_id=5일때의 데이터 묶음이 board에 할당됨(id, subject, comment,...)
    context = {'board':board}
    return render(request, 'bbsnote/board_detail.html', context)

@login_required(login_url='common:login')
def comment_create(request, board_id):
    if request.method =='POST':
        board = Board.objects.get(id=board_id)
        # comment = Comment(board=board, content=request.POST.get('content'), create_date=timezone.now())
        # comment.save()

        # Board와 Comment가 foreignKey로 연결되어있는 종속관계의 경우에는 위의 두 문장을 이렇게 한 줄로 쓸 수도 있다
        board.comment_set.create(content=request.POST.get('content'),create_date=timezone.now(), author=request.user)
    return redirect('bbsnote:detail', board_id=board_id)
        
    
@login_required(login_url='common:login')
def board_create(request):
    if request.method =='POST': # 요청된 정보가 POST로 왔으면 BoardForm이라는 클래스를 참조해서 요청된 정보롤 form이라는 변수에 담아라
        form = BoardForm(request.POST)
        if form.is_valid(): # 만약에 그 폼의 값이 있으면 그 값을 board에 저장하되, commit은 하지마라(mysql은 오토커밋이니까 오토커밋하지말라는 뜻)
            board = form.save(commit=False)
            board.author=request.user
            # board.create_date = timezone.now() #models.py에 자동으로 시간 저장되도록 이미 설정해두었기 때문에 없어도 되는 부분!
            board.save()  # create_date에 시간 할당하고나서 save해라(커밋해라)
            return redirect('bbsnote:index')#  저장까지 다 했으면 bbsnote의 index로 가라
    else: # POST로 요청이 오지 않았으면
        form = BoardForm()
    return render(request, 'bbsnote/board_form.html', {'form':form}) # 'form'이라는 키를 가진 애한테 form의 정보를 넘겨줘라


@login_required(login_url='common:login')
def board_modify(request, board_id):
    board = get_object_or_404(Board, pk=board_id) # 오류가 나면 오류 대신 404가 나오도록 처리
    if request.user != board.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('bbsnote:detail', board_id=board.id)
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.save()
            return redirect('bbsnote:detail', board_id=board.id)
    else:
        form=BoardForm(instance=board)
    context={'form' : form}
    return render(request, 'bbsnote/board_form.html', context)

@login_required(login_url='common:login')
def board_delete(request, board_id):
    board=get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('bbsnote:detail', board_id=board.id)
    board.delete()
    return redirect('bbsnote:index')

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    # 작성자가 아닌 경우 예외처리
    if request.user != comment.author:
        messages.error(request, "수정 권한이 없습니다!")
        # bbsnote의 detail에 board_id를 넘겨주는데, board_id가 현재 comment가 종속된 board의 id인 곳으로 가라
        return redirect('bbsnote:detail', board_id=comment.board.id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.save()
            return redirect('bbsnote:detail', board_id=comment.board.id)
    else:
        form = CommentForm(instance=comment)
    context={'comment':comment, 'form':form}
    return render(request, 'bbsnote/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, "삭제 권한이 없습니다!")
        return redirect('bbsnote:detail', board_id=comment.board.id)
    comment.delete()
    return redirect('bbsnote:detail', board_id=comment.board.id)

templates/bbsnote/board_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ board.subject }}</h2>
    <div class="col-11"> <!-- 본문 -->
        <div class="card">
            <div class="card-body">
                <div class="card-text">{{ board.content|linebreaksbr }}</div>
                <div class="d-flex justify-content-end">
                    {% if board.update_date|date:'Y-m-d A H:i' %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ board.update_date|date:'Y-m-d A H:i' }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ board.author.username }}</div>
                        <div>{{ board.create_date|date:'Y-m-d A H:i' }}</div>
                    </div>
                </div>
                <!-- 내가 쓴 글에서만 수정,삭제 버튼이 보임 -->
                {% if request.user == board.author %}
                <div class="my-3">
                    <a href="{% url 'bbsnote:board_modify' board.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'bbsnote:board_delete' board.id %}">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <h6 class="border-bottom my-3 py-2">{{board.comment_set.count}}개의 댓글이 있습니다.</h6>
    {% for comment in board.comment_set.all %}
    <div class="mt-3">
        <div class="comment py-2 text-muted">
            <span style="white-space: pre-line;">{{ comment.content|linebreaksbr }}</span>
            {% if request.user == comment.author %}
            <!-- url은 class_modify로 가고 comment_id를 넘겨주겠다 -->
            <a href="{% url 'bbsnote:comment_modify' comment.id %}" class="small">수정</a>
            <a href="#" class="small delete" data-uri="{% url 'bbsnote:comment_delete' comment.id %}">삭제</a>
            {% endif %}
            <div class="d-flex justify-content-end">
                {% if comment.update_date %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.update_date|date:'Y-m-d A H:i' }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.create_date|date:'Y-m-d A H:i' }}</div>
                </div>         
            </div>
        </div>
    {% endfor %}
    <form action="{% url 'bbsnote:comment_create' board.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="3" {%if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <input type="submit" value="댓글달기" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/bbsnote/board_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/bbsnote/board_list.html
{% extends 'base.html' %}
{% load bbsnote_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark"> 
            <th></th>           
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr class="text-center">
            <td>{{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-left">
                <a href="{% url 'bbsnote:detail' board.id %}">
                    {{ board.subject }}
                    {% if board.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        [{{ board.comment_set.count }}]
                    </span>
                    {% endif %}
                </a>                
            </td>
            <td> {{ board.author.username }}</td>
                        <!--대문자H로 시간 표시해야 오전/오후 구분됨-->
            <td>{{ board.create_date|date:'Y-m-d A H:i' }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지가 존재하면 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        <!-- 하단 페이지버튼이 현재 페이지를 기준으로 앞 뒤 2개씩 나오게 한 것-->
        {% if page_number >= board_list.number|add:-2 and page_number <= board_list.number|add:2 %}
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <!-- 로그인 안 하면 게시글 등록버튼 안 보임 -->
    {% if user.is_authenticated %}
    <a href="{% url 'bbsnote:board_create' %}" class="btn btn-primary">등록</a>
    {% endif %}   
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">    
    <input type="hidden" id="page" name="page" value="{{ page }}">    
</form>
{% endblock %}
<!-- page-link라는 클래스가 클릭이 되면 실행시켜라.
    #page : id가 페이지이면, 현재 데이터가 페이지라고 되어있는 값(data-page)을 넣어라 -->
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });     
});
</script>
{% endblock %}

templates/bbsnote/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}